# Generated by Django 4.1 on 2023-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempost',
            name='item_owner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
